### ISSUE TITLE
Duplicated cmake-modules in each submodule

### ISSUE THREAD

**Issue by makxenov** [NilFoundation/crypto3#143]
Most of crypto3 libraries have [cmake_modules](https://github.com/BoostCMake/cmake_modules) as a submodule. I see it useless because even if their versions are different, the local copy will not override the first loaded module. For example, in zkllvm environment, every `cm_*` function will be loaded from `zkllvm/cmake/modules`(root repository). I think that we should remove this duplication and have only one source of modules.

**Comment by x-mass** [comment]
This could potentially allow us to build them as stand-alone modules (group of modules most times, because of dependencies).
Say, you have installed entire crypto3, then clone only hash repo, make changes and could build it as is, not as part of crypto3.

Good question here is if we really need to provide users an ability to handle stand-alone modules. crypto3 is not that big to be fetched as a single package

**Comment by makxenov** [comment]
Fixed during crypto3 merging
